title: Florian Lautenschlager
description: PhD student, Computer Science departement at the University of Würzburg.
show_downloads: true
google_analytics:
work-url: https://www.dmir.org/staff/lautenschlager
theme: jekyll-theme-cayman
